/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ingenic_glass_rtspserver_service_Live555MediaServer */

#ifndef _Included_com_ingenic_glass_rtspserver_service_Live555MediaServer
#define _Included_com_ingenic_glass_rtspserver_service_Live555MediaServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ingenic_glass_rtspserver_service_Live555MediaServer
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ingenic_glass_rtspserver_service_Live555MediaServer_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_ingenic_glass_rtspserver_service_Live555MediaServer
 * Method:    nativeSetup
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_ingenic_glass_rtspserver_service_Live555MediaServer_nativeSetup
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_ingenic_glass_rtspserver_service_Live555MediaServer
 * Method:    nativeStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ingenic_glass_rtspserver_service_Live555MediaServer_nativeStart
  (JNIEnv *, jobject);

/*
 * Class:     com_ingenic_glass_rtspserver_service_Live555MediaServer
 * Method:    nativeStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ingenic_glass_rtspserver_service_Live555MediaServer_nativeStop
  (JNIEnv *, jobject);

/*
 * Class:     com_ingenic_glass_rtspserver_service_Live555MediaServer
 * Method:    nativeRelease
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ingenic_glass_rtspserver_service_Live555MediaServer_nativeRelease
  (JNIEnv *, jobject);

/*
 * Class:     com_ingenic_glass_rtspserver_service_Live555MediaServer
 * Method:    nativeWriteLiveH264
 * Signature: ([BIII)V
 */
JNIEXPORT void JNICALL Java_com_ingenic_glass_rtspserver_service_Live555MediaServer_nativeWriteLiveH264
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
